spring:
  # Knife4j ?? SpringDoc OpenAPI 3.0???? springdoc ????
  doc:
    openapi:
      # ????????????
      info:
        title: ????????        # ????
        description: ????Knife4j OpenAPI3???????  # ????
        version: 1.0.0                # ????
        contact:
          name: ????
          email: dev@example.com

      packages-to-scan: com.example.demo.controller
      # ????????????????
      paths-to-exclude: /error,/actuator/**
    # Knife4j ????
    knife4j:
      enable: true                    # ?? Knife4j ????
      setting:
        language: zh_cn               # ????????
        enable-swagger-models: true   # ???????
        enable-document-manage: false # ??????????????
        enable-version: false         # ??????????????